FROM debian:stable-slim

ENV GOLANG_VERSION 1.12.6
ENV GOLANG_SHA256SUM dbcf71a3c1ea53b8d54ef1b48c85a39a6c9a935d01fc8291ff2b92028e59913c

ENV GOPATH=/go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH
ENV CGO_LDFLAGS="-Wl,-rpath=/usr/local/lib"

ENV DEBIAN_FRONTEND noninteractive
ENV TERM linux
ENV INITRD No
ENV LANG C.UTF-8

RUN apt-get update -yqq && \
    apt-get install apt-file bash -yqq && \
    apt-get install -yqq --no-install-recommends \
        make \
        gcc \
        g++ \
        git \
        curl \
        ca-certificates \
        xz-utils && \
    apt-get clean && \
    rm -rf \
        /var/lib/apt/lists/* \
        /tmp/* \
        /var/tmp/* \
        /usr/share/man \
        /usr/share/doc \
        /usr/share/doc-base && \
    \
    \
    cd /usr/local/src && \
    curl -fsSL https://golang.org/dl/go${GOLANG_VERSION}.linux-amd64.tar.gz -o golang.tar.gz && \
    echo "${GOLANG_SHA256SUM} golang.tar.gz" | sha256sum -c - && \
    tar -C /usr/local -xzf golang.tar.gz && \
    rm -rf /usr/local/src/* && \
    go get -u github.com/golang/dep/cmd/dep  && \
    go get -u github.com/revel/cmd/revel

VOLUME /go/src/github.com/nxsw/golang-revel-docker-compose/
WORKDIR /go/src/github.com/nxsw/golang-revel-docker-compose/

RUN ln -s /usr/local/go/src/runtime /go/src/runtime
